export const words = {
    "reservation": "예약",
    "rental": "대여(의)",
    "additional": "추가의",
    "in_advance": "미리, 사전에",
    "cliff": "절벽",
    "passenger": "승객",
    "be_about_to_do": "막 ~하려 하다",
    "glow": "붉은 빛",
    "athlete": "운동선수",
    "progress": "진전, 진보",
    "drive": "추진력",
    "utilize": "활용하다",
    "gear": "장치, 장비",
    "maximize": "극대화하다",
    "sustain": "유지시키다",
    "mindset": "마음가짐, 사고방식, 태도",
    "strengthen": "강화하다",
    "polish": "다듬다",
    "in_the_first_place": "애초에",
    "vigor": "활력, 활기",
    "pure": "순수한",
    "objective": "객관적인",
    "perspective": "관점",
    "version": "버전, 견해, 설명",
    "precisely": "바로, 정확하게",
    "universal": "보편적인",
    "authoritative": "권위 있는, 권위적인",
    "theoretical_construct": "이론적 구성물",
    "intelligible": "(쉽게) 이해할 수 있는",
    "illusion": "환영",
    "overlook": "간과하다",
    "notion": "개념",
    "paradox": "역설",
    "engagement": "참여, 관여",
    "awareness": "인식",
    "in_whole_or_in_part": "전체로든 부분으로든",
    "conflicted": "갈등을 겪는",
    "current": "현재의",
    "location": "위치",
    "armed_with": "~로 무장한",
    "bystander": "방관자",
    "stakeholder": "이해관계자",
    "vulnerable": "상처를 입기 쉬운",
    "considerable": "주목할 만한, 상당한",
    "psychologist": "심리학자",
    "concept": "개념",
    "central": "중추 신경의",
    "neurally": "신경으로",
    "implement": "실행[시행]하다",
    "state": "상태",
    "as_for": "~에 관해 말하면",
    "architecture": "구조, 건축",
    "interpret": "해석하다",
    "categorize": "범주화하다",
    "vary": "다르다, 다양하다",
    "appropriate": "적절한",
    "invariant": "불변의, 변함없는",
    "universal": "보편적인",
    "evolution": "진화, 발전",
    "plastic": "바뀌기 쉬운, 가소성의",
    "modify": "수정하다",
    "specific": "특정한",
    "anthropologist": "인류학자",
    "stimuli": "자극",
    "cognitive": "인지적인",
    "intelligence": "지력, 지능, 이해력",
    "synergistic": "서로 도움을 주는, 상승적인",
    "arise": "생기다, 발생하다",
    "contribution": "기여, 이바지",
    "agent": "행위자, 동인",
    "telecommuting": "재택근무",
    "coordinate": "조정하다",
    "agenda": "과제, 안건",
    "service_animal": "도우미 동물(장애인을 돕도록 훈련 받은 동물)",
    "sheep_dog": "양몰이 개",
    "artificial_intelligence": "인공 지능",
    "resident": "거주민[거주자]",
    "patent": "특허",
    "population": "인구 (집단)",
    "link": "연결하다",
    "reproduce": "번식하다",
    "acquisition": "획득, 습득",
    "transformation": "변형, 변화",
    "rely_on": "~에 의지하다",
    "precise": "정확한",
    "unequivocal": "분명한",
    "survive": "살아남다",
    "framework": "구조, 뼈대",
    "profound": "깊은",
    "assert": "주장하다",
    "revise": "개정하다",
    "core": "핵심",
    "constitute": "~으로 이루어지다",
    "framework": "체계, 구조",
    "gradual": "점진적인",
    "emerge": "나타나다",
    "evolution": "진화",
    "personality": "개성, 성격",
    "genetic": "유전적인",
    "determinant": "결정적인 요인",
    "temperament": "성격, 기질",
    "inherit": "상속받다",
    "trait": "특성, 특징",
    "environmental": "환경의",
    "factor": "요소",
    "interaction": "상호 작용",
    "complex": "복잡한",
    "interplay": "상호 작용, 교감",
    "influence": "영향을 미치다",
    "comprise": "~로 이루어지다",
    "unique": "독특한",
    "combination": "조합",
    "shape": "형성하다",
    "individual": "개인의",
    "expression": "표현",
    "emphasize": "강조하다",
    "profound": "깊은",
    "impact": "영향",
    "shape": "형성하다",
    "interaction": "상호 작용",
    "dynamic": "동적인",
    "complexity": "복잡성",
    "adapt": "적응하다",
    "surrounding": "주변의",
    "context": "맥락, 문맥",
    "embrace": "받아들이다",
    "cope_with": "~을 처리하다",
    "adjust": "조절하다",
    "embrace": "받아들이다",
    "navigate": "다루다",
    "challenge": "도전, 어려움",
    "emerge": "나타나다",
    "resilient": "탄력 있는",
    "flexible": "유연한",
    "versatile": "다재다능한",
    "thrive": "번영하다",
    "prosper": "번창하다",
    "succeed": "성공하다",
    "excel": "뛰어나다",
    "innovate": "혁신하다",
    "lead": "이끌다",
    "inspire": "영감을 주다",
    "motivate": "동기를 부여하다",
    "create": "창조하다",
    "contribute": "기여하다"
}
